/*
CREATE DATABASE
=============================
PURPOSE:
CREATE DATABASE, SCHEMA, 
CHECK IF THERE ANY DATABASE WITH THE NANE DATAWAREHOUSE THEN DROP IT
*/
USE master
GO
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'Datawarehouse')
BEGIN
	ALTER DATABASE Datawarehouse SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE Datawarehouse;
END;

CREATE DATABASE Datawarehouse;

USE Datawarehouse;
GO
CREATE SCHEMA bronze;
GO
CREATE SCHEMA silver;
GO
CREATE SCHEMA gold;
